export const ALL_PERMISSIONS = {
  "admin:view": { name: "Access Admin Hub" },
  "users:view": { name: "View Users" },
  "users:create": { name: "Create Users" },
  "users:update": { name: "Update Users" },
  "users:delete": { name: "Delete Users" },
  "roles:view": { name: "View Roles" },
  "roles:manage": { name: "Manage Roles" },
  "pos:view": { name: "Access POS" },
  "pos:create_order": { name: "Create Orders" },
  "kitchen:view": { name: "Access Kitchen" },
  "kitchen:mark_ready": { name: "Mark Ready" },
  "cashier:view": { name: "Cashier View" },
  "cashier:approve_order": { name: "Approve Order" },
  "cashier:cancel_order": { name: "Cancel Order" },
  "cashier:refund_order": { name: "Refund Order" },
  "cashier:close_session": { name: "Close Session" },
  "cashier:view_reports": { name: "View Cashier Reports" },
  "pos:apply_discount": { name: "Apply Discount" },
  "catalog:view": { name: "View Catalog" },
  "catalog:manage": { name: "Manage Catalog" },
  "inventory:view": { name: "View Inventory" },
  "inventory:manage": { name: "Manage Inventory" },
  "reports:view": { name: "View Reports" },
  "discounts:view": { name: "View Discounts" },
  "discounts:manage": { name: "Manage Discounts" },
  "branches:manage": { name: "Manage Branches" },
  "settings:manage": { name: "Manage Settings" },
  "orders:pickup": { name: "Access Pickup" },
} as const;

export type PermissionKey = keyof typeof ALL_PERMISSIONS;
