name: Deploy to VPS

on:
  push:
    branches:
      - main  # Set this to master if your primary branch is named master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/spacca-pos
            git pull origin main
            docker compose up -d --build
